version: '3.8'

services:
  nodejs-api:
    build: ./nodejs-api
    ports:
      - "3000:3000"

  java-api:
    build: ./java-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  python-api:
    build: ./python-api
    ports:
      - "5000:5000"

  go-api:
    build: ./go-api
    ports:
      - "8000:8000"

  csharp-api:
    build: ./csharp-api
    ports:
      - "80:80"

  kafka:
    build: ./kafka

  rabbitmq:
    build: ./rabbitmq
    ports:
      - "15673:15672" # Changed port to 15673

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432" # Changed port to 5433

