version: '3.8'

services:
  nodejs-api:
    build: ./nodejs-api
    ports:
      - "3000:3000"

  java-api:
    build: ./java-api
    ports:
      - "8080:8080"

  python-api:
    build: ./python-api
    ports:
      - "5000:5000"

  go-api:
    build: ./go-api
    ports:
      - "8000:8000"

  csharp-api:
    build: ./csharp-api
    ports:
      - "80:80"

  kafka:
    build: ./kafka