apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api-deployment
  labels:
    app: nodejs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      imagePullSecrets:                 # Move this section here
      - name: docker-registry-secret
      containers:
      - name: nodejs-api
        image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/nodejs-api:15
        ports:
        - containerPort: 3000