apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api-deployment
  labels:
    app: nodejs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      imagePullSecrets:                 
      - name: docker-registry-secret
      containers:
      - name: nodejs-api
        image: "{{ .Values.nodejs-api.image }}:{{ .Values.nodejs-api.tag }}"
        imagePullPolicy: "{{ .Values.global.pullPolicy }}"
        ports:
        - containerPort: 3000
