apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-api-deployment
  labels:
    app: csharp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-api
  template:
    metadata:
      labels:
        app: csharp-api
    spec:
      imagePullSecrets:                 # Move this section here
      - name: docker-registry-secret
      containers:
      - name: csharp-api
        image: 172.19.74.2:8083/repository/docker-registry/multi-microservice/csharp-api:15
        ports:
        - containerPort: 80