apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    {{- include "java-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "java-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "java-api.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:                 
      - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        - secretRef:
            name: {{ .Release.Name }}-secret