nginx:
  image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/nginx
  tag: 15
  replicaCount: 1
   
csharp-api:
  image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/csharp-api
  tag: 15
  replicaCount: 1

python-api:
  image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/python-api
  tag: 15
  replicaCount: 1

java-api:
  image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/java-api
  tag: 15
  replicaCount: 1

go-api:
  image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/go-api
  tag: 15
  replicaCount: 1
  noderole: common

nodejs-api:
  image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/nodejs-api
  tag: 15
  replicaCount: 1

global:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

