apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api-deployment
  labels:
    app: java-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      imagePullSecrets:                 # Move this section here
      - name: docker-registry-secret
      containers:
      - name: java-api
        image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/java-api:15
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: java-api-config
        - secretRef:
            name: java-api-secret
