replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent


imagePullSecrets:
  name: docker-registry-secret
service:
  name: csharp-api-service
  type: NodePort
  targetPort: 80
  port: 4000
  nodePort: 30000

container:
  name: csharp-api

