apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  labels:
    app: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      imagePullSecrets:                 # Move this section here
      - name: docker-registry-secret
      containers:
      - name: go-api
        image: 172.19.79.173:8083/repository/docker-registry/multi-microservice/go-api:18
        ports:
        - containerPort: 8000